sudo: required
language: generic

services:
  - docker


after_success:
  - docker build -t fazale/backend ./backend
  - docker build -t fazale/nginx ./nginx
  - docker build -t fazale/client ./client-frontend
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  - docker push fazale/client
  - docker push fazale/nginx
  - docker push fazale/backend



deploy:
provider: elasticbeanstalk
region: us-east-1
app: sample-docker
env: Sampledocker-env
bucket_name: elasticbeanstalk-us-east-1-675359431836
bucket_path: docker-multi
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY