version: '3'

services:
  mongo:
    image: 'mongo:bionic'
    expose: 
      - 27017 
    ports: 
      - "27018:27017"
  node-app:
    build: 
        context: ./backend
        dockerfile: Dockerfile.dev
    ports: 
        - "8080:8080"
    volumes:
    #     - /backend/node_modules
        - ./backend:/backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose: 
        - 8080
  client-frontend:
    build:
      context: ./client-frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
        #     - /frontend/node_modules
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true  
    expose: 
      - 3000
  nginx:
    depends_on:
      - node-app
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3900:80'
  